environment:
  nodejs_version: "9"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

cache:
 - node_modules
 - '%APPDATA%\npm-cache'

build: off
