# Work-around for https://github.com/travis-ci/travis-ci/issues/8836
sudo: true
language: node_js
node_js:
  - node
before_script:
  - node --version
  - npm --version
  - npm install
script:
  - npm run test
os:
  - linux
cache:
  directories:
  - node_modules
addons:
  firefox: latest
  chrome: stable
