version: 2
jobs:
  build:
    macos:
      xcode: "9.1.0"
    steps:
      - checkout
      - run: brew upgrade npm
      - run: brew install caskroom/cask/firefox caskroom/cask/google-chrome
      - run: node --version
      - run: npm --version
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm run test
